== opsutil
A simple set of devops utilities designed to streamline development of cloud-enabled applications
on Debian-based systems.


=== Utilities

==== setup-nopass-sudo
Sets up no-password sudo on the local machine. This can be fully unattended by providing
command line args. See help.

To see help:
----
bash <(curl -s https://raw.github.com/dhsu/opsutil/master/bin/setup-nopass-sudo) -h
----

To run (see help for command line args):
----
bash <(curl -s https://raw.github.com/dhsu/opsutil/master/bin/setup-nopass-sudo)
----

==== setup-chef-server
Turns the local machine into a chef server. This can be fully unattended by providing
command line args. For a fully unattended install, you should also first run `setup-nopass-sudo`.

To see help:
----
bash <(curl -s https://raw.github.com/dhsu/opsutil/master/bin/setup-chef-server) -h
----

To run (see help for command line args):
----
bash <(curl -s https://raw.github.com/dhsu/opsutil/master/bin/setup-chef-server)
----

==== setup-knife-client
Turns the local machine into a knife client. This can be fully unattended by providing
command line args. For a fully unattended install, you should also first run `setup-nopass-sudo`.
You must remember to copy the client and validation keys to the ~/.chef folder.
There will be a script provided in an upcoming release that automates key generation
and transfer.

To see help:
----
bash <(curl -s https://raw.github.com/dhsu/opsutil/master/bin/setup-knife-client) -h
----

To run (see help for command line args):
----
bash <(curl -s https://raw.github.com/dhsu/opsutil/master/bin/setup-knife-client)
----

=== Coming Soon
Script to setup client and validation keys

